# Generated by Django 2.2.7 on 2019-11-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
